program4: prog4.c makefile
	gcc prog4.c -o prog4
	./prog4

program5: prog5.c makefile
	gcc prog5.c -o prog5
	./prog5

program6: prog6.c makefile
	gcc prog6.c -o prog6
	./prog6

program7: prog7.c makefile
	gcc prog7.c -o prog7
	./prog7

program8: prog8.c makefile
	gcc prog8.c -o prog8
	./prog8





