program19_1: prog19_1.c makefile
	gcc prog19_1.c -o prog19_1
	./prog19_1

program19_2: prog19_2.m makefile
	gcc -arch i386 -o prog19_2 -l objc prog19_2.m
	./prog19_2

program19_3: prog19_3.cpp makefile
	g++ prog19_3.cpp -o prog19_3
	./prog19_3

program19_4: prog19_4.cs makefile
	mcs prog19_4.cs
	mono prog19_4.exe







