program1: prog1.c makefile
	gcc prog1.c -o prog1
	./prog1

program2: prog2.c makefile
	gcc prog2.c -o prog2
	./prog2 2 5

program2_debug: prog2.c makefile
	gcc -D DEBUG prog2.c -o prog2
	./prog2 5 10

program3_macro: prog3.c makefile
	gcc prog3.c -o prog3
	./prog3 8 12

