Exercise2: prog2.c makefile
	gcc prog2.c -o prog2
	./prog2

Exercise3: prog3.c makefile
	gcc prog3.c -o prog3
	./prog3

Exercise4: prog4.c makefile
	gcc prog4.c -o prog4
	./prog4

Exercise5: prog5.c makefile
	gcc prog5.c -o prog5
	./prog5

Exercise6: prog6.c makefile
	gcc prog6.c -o prog6
	./prog6


 
 
