program2: prog2.c makefile
	gcc prog2.c -o prog2
	./prog2 < input > output

program2_inputonly: prog2.c makefile
	gcc prog2.c -o prog2
	./prog2 < input

program2_outputonly: prog2.c makefile
	gcc prog2.c -o prog2
	./prog2 > output

