program2: prog2.c makefile
	gcc prog2.c -o prog2
	./prog2

program3: prog3.c makefile
	gcc prog3.c -o prog3
	./prog3

program4: prog4.c makefile
	gcc prog4.c -o prog4
	./prog4

program5: prog5.c makefile
	gcc prog5.c -o prog5
	./prog5

program6: prog6.c makefile
	gcc prog6.c -o prog6
	./prog6

program7: prog7.c makefile
	gcc prog7.c -o prog7
	./prog7

program8: prog8.c makefile
	gcc prog8.c -o prog8
	./prog8

program9: prog9.c makefile
	gcc prog9.c -o prog9
	./prog9

program10: prog10.c makefile
	gcc prog10.c -o prog10
	./prog10

program11: prog11.c makefile
	gcc prog11.c -o prog11
	./prog11

program12: prog12.c makefile
	gcc prog12.c -o prog12
	./prog12









