program1: prog1.c makefile
	gcc prog1.c -o prog1
	./prog1

program2: prog2.c makefile
	gcc prog2.c -o prog2
	./prog2

program3: prog3.c makefile
	gcc prog3.c -o prog3
	./prog3

program4: prog4.c makefile
	gcc prog4.c -o prog4
	./prog4

