program1: prog1.c makefile
	gcc prog1.c -o prog1
	./prog1

program2: prog2.c makefile
	gcc prog2.c -o prog2
	./prog2

program3: prog3.c makefile
	gcc prog3.c -o prog3
	./prog3

program4: prog4.c makefile
	gcc prog4.c -o prog4
	./prog4

program5: prog5.c makefile
	gcc prog5.c -o prog5
	./prog5

program6: prog6.c makefile
	gcc prog6.c -o prog6
	./prog6

program7: prog7.c makefile
	gcc prog7.c -o prog7
	./prog7

program8: prog8.c makefile
	gcc prog8.c -o prog8
	./prog8

program9: prog9.c makefile
	gcc prog9.c -o prog9
	./prog9

program10: prog10.c makefile
	gcc prog10.c -o prog10
	./prog10

program11: prog11.c makefile
	gcc prog11.c -o prog11
	./prog11

program12: prog12.c makefile
	gcc prog12.c -o prog12
	./prog12

program13: prog13.c makefile
	gcc prog13.c -o prog13
	./prog13

program14: prog14.c makefile
	gcc prog14.c -o prog14
	./prog14

program15: prog15.c makefile
	gcc prog15.c -o prog15
	./prog15

program16: prog16.c makefile
	gcc prog16.c -o prog16
	./prog16
